### PR TITLE
Save theme, code mirror options and preview state on localStorage

### LINKED ISSUE #76: Dark mode deactivates on page reload
After activating dark mode, I discovered that on every page reload, it is deactivated.

There should be settings to save the current theme on the browser's storage system.

Thank you : )

### PR DESCRIPTION
**Pull request by ashinzekene**
Functionality works. Open to a way to make this better. Feels like there's so much repetition

Fixes #76

### CODE REVIEW

**Comment by ashinzekene** [comment]
Okay. I actually thought of that too. It also means I'd have to move `previewMarkdown` too

**Comment by ashinzekene** [comment]
Done

**Comment by taniarascia** [comment]
@ashinzekene sorry, I didn't get a notification. I'll check it out. :)

**Comment by taniarascia** [comment]
This is great! Should we be making more selectors?

**Comment by ashinzekene** [comment]
Thanks.

Only if we need them

**Pull request merged**
