### PR TITLE
Add scratchpad

### PR DESCRIPTION
**Pull request by Mxchaeltrxn**
Addresses #248

I've renamed scratchpad to inbox because inbox is used in the 'getting things done' methodology. If we want it to be something else, it can be changed.

I did not update the icon for the inbox because I don't know how to draw icons. 

I have implemented this such that the inbox note gets created on start up and there is no way for the user to create or delete it. This means that existing users cannot use this feature. I figured this might be okay since everything will be changing once you add the github sync anyway.

### CODE REVIEW

**Comment by taniarascia** [comment]
Hi! Thanks for your work on this. It's looking good! A few notes:

- Since there's only one "note" in this folder, there would be no need for the NoteList sidebar. This could easily be fixed by conditionally showing the NoteList based on whether or not it's the active folder.

```js
return activeFolder !== Folder.INBOX ? (
  <aside className="note-sidebar"> ... </aside>
) : null
```

Regarding the name, inbox does sound nice, but I don't think it's very accurate in this specific situation. There is nothing incoming, and it in no way relates to communication, chat, notifications, etc. It's simply an empty place to write something. I think Scratchpad is still a more accurate term for that.

Regarding the icon, no drawing or illustration knowledge is necessary. The icons come from React Feather: https://bit.dev/feathericons/react-feather / Feather: https://feathericons.com/. I think `FileText` or `Edit` would be good choices here. 

And I think that's fine for now, in the complete implementation we'd probably want the default note to keep coming back if it was deleted or not present.

**Comment by taniarascia** [comment]
"Today" might be another option for the name, though it seems a little more limiting.

**Comment by Mxchaeltrxn** [comment]
I removed the notelist sidebar while viewing the scratchpad and added an icon. I also made it so that the scratchpad note keeps will come back if it's not there on a page refresh. I agree that scratchpad sounds better for this use case so changed inbox to scratchpad.

After adding the scratchpad note, I also found some weird behaviours when deleting a note. It makes me think we should add some tests but I am not sure. I don't have a lot of experience with frontend testing.

**Comment by taniarascia** [comment]
What bugs did you notice? I’ll take a look at this soon. Front end tests are always welcome, there are a many example files to look at.

**Comment by taniarascia** [comment]
This fixes the trash issue, but I'm going to see if I can write it to be cleaner.

```js
const getNewActiveNoteId = (
  notes: NoteItem[],
  oldNoteId: string,
  activeCategoryId: string,
  activeFolder: Folder
): string => {
  const filterableNotes = notes.filter(note => !note.scratchpad)
  let newActiveNotes

  // If trash is not active, get all notes that aren't in the trash
  if (activeFolder !== Folder.TRASH) {
    // If in an active category, additionally only filter category matches
    if (activeCategoryId) {
      newActiveNotes = filterableNotes.filter(
        note => !note.trash && note.category === activeCategoryId
      )
    } else {
      newActiveNotes = filterableNotes.filter(note => !note.trash)
    }
  } else {
    // If in the trash, only get trash notes
    newActiveNotes = filterableNotes.filter(note => note.trash)
  }

  // Find the note that got deleted
  const trashedNoteIndex = newActiveNotes.findIndex(note => note.id === oldNoteId)

  // If it was the first note, get the next new first note
  if (trashedNoteIndex === 0 && newActiveNotes[1]) {
    return newActiveNotes[1].id
  }
  // Otherwise, if a previous note exists, use that
  if (newActiveNotes[trashedNoteIndex - 1]) {
    return newActiveNotes[trashedNoteIndex - 1].id
  }

  // If the note is the last one in the list, return no active note
  return ''
}
```

**Comment by taniarascia** [comment]
You’ll have to pass activeFolder to every instance of that function.

**Comment by Mxchaeltrxn** [comment]
@taniarascia 
Sorry I accidentally didn't stage my commit before amending.

Right. So the bug was fixed by my changes to getNewActiveNoteId. The scratchpad would show up in the editor after deleting a note because it wasn't accounted for in the old getNewActiveNoteId function. 

In regards to tests, I might have a look at the other test PRs.

**Comment by taniarascia** [comment]
@all-contributors please add @Mxchaeltrxn for code

**Pull request merged**
