### PR TITLE
Add counts to folders and categories #17

### PR DESCRIPTION
**Pull request by hankolsen**

### CODE REVIEW

**Comment by hankolsen** [comment]
Ah, sorry, I managed to push a possible fix for #11 into the same pull request :(

**Comment by taniarascia** [comment]
Is there any chance you can separate them? :) After seeing badges next to everything, it's a bit busy and overwhelming, so maybe it should only be an option but not the default...

**Comment by hankolsen** [comment]
Removed the keybinding stuff, so this pull request is just the badge count.
The setting to hide the badge count is not implemented yet.

**Comment by hankolsen** [comment]
Maybe stying the counts as just numbers without the badge could make it less "in your face"..?

**Comment by hankolsen** [comment]
image

**Comment by taniarascia** [comment]
Going to hold off on this one for now, just because it starts to get a bit cluttered.

**Pull request closed without merging**
