### PR TITLE
Bug fix for #373

### LINKED ISSUE #373: [Bug] Do not continuously allow "New note"
**To Reproduce**
- Go to trash
- Create new note
- Go to trash
- Create new note
- Go to trash
- Create new note

**Expected behavior**
If one "New note" exists, no new ones should be created

**Actual behavior**
Several "New note" notes will be created. When you click on another note, the duplicates will be removed, but they shouldn't have been created.

### PR DESCRIPTION
**Pull request by kodyclemens**
## Description

Fixed bug where multiple new notes could be created. With this change if one "New note" exists, no new ones are created.

Added Cypress test specifically for this issue. Fixed two other failing e2e tests that were relying on the ability to create multiple new notes.

Fixes #373 

## Browser Checklist

This PR has been tested in the following browsers:

- [x] Chrome
- [ ] Firefox
- [ ] Safari

### CODE REVIEW

**Comment by taniarascia** [comment]
Hi! This puts the application in a weird state where if you create a new note, then go to trash or favorites and try to create a new note, nothing will happen. This would be very confusing for a user. It would be better to delete the note when navigating to a new section, or something like that.

**Comment by kodyclemens** [comment]
Hey @taniarascia I am curious of your thoughts on these changes:

- New notes are removed upon switching to new folder or category
- Context menu options removed for new notes until the note has actually been given some content by the user
- Content option added for only new notes; instructs user to add content before having access to normal context options
- New notes are no longer draggable until given content
- Adjusted tests that were relying on being able to move new notes through dragging and content options
- Changed beforeEach in note.test.ts and category.test.ts to use a unique note instead of a new note; majority are test case changes on the assertion of note list length

**Comment by taniarascia** [comment]
Looks great, thanks for all this! The changes are very good. My only comments are about some code style things:

For example, anything that looks like this:

```js
      {clickedNote.text === '' ? (
        <div className="nav-item">
          <AlertTriangle size="16" />
          {LabelText.ADD_CONTENT_NOTE}
        </div>
      ) : null}
```

Can be written as:

```js
     {clickedNote.text !== '' && (
        <div className="nav-item">
          <AlertTriangle size="16" />
          {LabelText.ADD_CONTENT_NOTE}
        </div>
      )}
```

No need for a ternary or `null`. You have ` {clickedNote.text === '' ? null :` then later `clickedNote.text === ''` again in the same file, it would be best to deal with them once.

My other comment is since `note === ''` is used a lot, making a helper function like:

```js
function isDraftNote(note) {
   return note === ''
}
```

And using it throughout the code will make it more clear.

**Comment by kodyclemens** [comment]
@taniarascia good evening, I have made the changes & thanks for the feedback!

**Comment by taniarascia** [comment]
Awesome, thank you!

**Pull request merged**
