### PR TITLE
fix: your contributor bot doesn't like me, that's ok

### PR DESCRIPTION
**Pull request by jackson-elfers**
Please read the [Contribution Guidelines](../CONTRIBUTING.md) before opening a pull request.

## Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #

## Browser Checklist

This PR has been tested in the following browsers:

- [ ] Chrome
- [ ] Firefox
- [ ] Safari

### CODE REVIEW

**Comment by taniarascia** [comment]
@all-contributors please add @jackson-elfers for code

**Comment by taniarascia** [comment]
@all-contributors please add @jackson-elfers for code

**Comment by taniarascia** [comment]
Manually updating the autogenerated files doesn't turn out well. Sorry, the bot didn't recognize what came after the hyphen. :( Fixed it now.

**Comment by jackson-elfers** [comment]
Hey it's all good, thanks have a good one.

**Pull request closed without merging**
