### PR TITLE
inital setup of jest and 1 test for NoteOptions

### PR DESCRIPTION
**Pull request by dagda1**
I've done an initial setup of jest, ts-jest and friends with one passing test in `NoteOptions`.

#14 did not mention where the tests should be.  I like to colocate mine by the file but others like a `__tests__` directory or something.

This is a starter, let me know if you want anything else.

### CODE REVIEW

**Comment by taniarascia** [comment]
Awesome, thank you. This is a great help. The folder naming convention you used is what I prefer.

**Comment by dagda1** [comment]
@taniarascia ok, so where would the test go?  would the folder structure of `./tests`, match the folder structure of `./src`.  This is why I colocate them because you then have to keep 2 folder structures in sync.

BUT!!!! This is your repo and I will abide by your wishes :).

**Comment by taniarascia** [comment]
In the past, I've used a `tests` folder and kept the structure in sync, but I'd be happy to try out colocating them. It seems smarter and easier to find things. :)

**Comment by dagda1** [comment]
thank you, let me know if there are any other issues i can look at.

**Pull request merged**
