### PR TITLE
refactor: remove lodash, create debounceEvent helper, regex escape

### LINKED ISSUE #272: [Refactor] Remove Lodash and Moment
Lodash is only used in one file, and moment is only used to set the date of the note being created or synced.

### PR DESCRIPTION
**Pull request by jackson-elfers**
Please read the [Contribution Guidelines](../CONTRIBUTING.md) before opening a pull request.

## Description

Removes lodash package and replaces with native helpers.
[debounce.ts](https://gist.github.com/ca0v/73a31f57b397606c9813472f7493a940)
[Escape string for use in Javascript regex](https://stackoverflow.com/questions/3446170/escape-string-for-use-in-javascript-regex)

Fixes #272 

## Browser Checklist

This PR has been tested in the following browsers:

- [x] Chrome
- [ ] Firefox
- [ ] Safari

### CODE REVIEW

**Comment by taniarascia** [comment]
@all-contributors please add jackson-elfers  for code.

**Comment by taniarascia** [comment]
@all-contributors please add jackson-elfers for code.

**Comment by jackson-elfers** [comment]
Hey @taniarascia I think your contributor bot got the wrong jackson haha. It's all good.

**Comment by taniarascia** [comment]
Sorry about that. Apparently the bot  didn't recognize what came after the hyphen without a @. Whoops!

**Pull request merged**
