### PR TITLE
Enable categories to be renamed by double clicking on them.

### LINKED ISSUE #36: [Categories] Rename categories
It would be nice if we could rename a category, instead of removing it and recreate it

### PR DESCRIPTION
**Pull request by jeffslofish**
Closes #36

### CODE REVIEW

**Comment by taniarascia** [comment]
I encountered some bugs while playing around with this one. After enough double clicking, the app would crash, with some `insertBefore` error. Happebed twice. Need to see if I can replicate. Also, it seemed to be making a bunch of `nbsp;`

Screen Shot 2019-10-16 at 12 58 24 AM

**Comment by jeffslofish** [comment]
I was in bed trying to fall asleep and I thought of this issue as well. Since the id of the category is simply the initial category name, if you rename a category from say, "test" to "test1" and then try to make a new category called "test", it won't let you because "test1" has an id of "test". Maybe the category ids should be UUIDs (or whatever they are) for the notes?

**Comment by taniarascia** [comment]
I used the IDs to make the categories unique, though. I don't want you to be able to make `HEALTH` and `Health` and `health`. They could instead have `id`, `short-name`, and `name`.

**Comment by taniarascia** [comment]
1. Instead of updating the category immediately, it should update the temp category state. This will ensure the checks - no duplicates, no category too long - apply.
2. Create unique `id` with uuid and `short-name`, to ensure unique IDs but a short name to check the values.

**Pull request merged**
