### PR TITLE
Download all notes as zip

### LINKED ISSUE #364: [Feature] Add ability to download all notes as a zip
Right now, you can download a single or multiple notes. It would be good to add the ability to download all notes at once from the settings menu.

### PR DESCRIPTION
**Pull request by kodyclemens**
## Description

Ability to download all notes as a zip file added to the settings menu. A new section temporarily named `Data Management` was added. Created new `SvgOption` component to allow display of clickable svg (accepts a draw path). `svg` class created in `_helpers.scss`.

Fixes #364

## Browser Checklist

This PR has been tested in the following browsers:

- [x] Chrome
- [ ] Firefox
- [ ] Safari

### CODE REVIEW

**Comment by taniarascia** [comment]
Hi again, a few notes:

- There is already React feather for icons, no need to bring in a new Svg element.
- The Svg element breaks the settings modal by creating a large horizontal scroll.
- This PR also contains code from the other draft notes PR

Please update to only include code for downloading notes as a zip and use the existing icon set. Thanks!

**Comment by kodyclemens** [comment]
Thanks for the feedback @taniarascia 👍🏻  I will make the changes mentioned here and on the other PR tomorrow.

**Comment by taniarascia** [comment]
Sounds good!

**Comment by kodyclemens** [comment]
@taniarascia Requested changes have been made

**Comment by taniarascia** [comment]
Definitely looking better, thanks! I still have a few issues that are preventing me from merging this in:

- Although the "Download all notes" button looks like just text, and does not have a pointing cursor, it still performs an action when I click on it, which was unexpected.
- There is now a component called `<SvgOption>` but there is nothing SVG about it, it does not seem that this component is necessary.
- The clickable/mouse pointer area of the icon is very small.

My suggestion would be to simply have "Download all notes" plus the icon in a Button (perhaps you could make a IconButton component). It would be obvious where the click area is, and the component could potentially be useful elsewhere.

Thanks again for the contribution!

**Comment by taniarascia** [comment]
P.S. I updated the settings page to have tabs, so you can now put the "Data management" option in a new tab. :)

**Comment by kodyclemens** [comment]
Good feedback, I will work on this 💯

**Comment by taniarascia** [comment]
Also, we'll have to make sure multiple files with the same can be downloaded (that's a bug ticket so doesn't have to be done here).

**Comment by kodyclemens** [comment]
@taniarascia please let me know what you think of these changes

**Comment by taniarascia** [comment]
Great, thanks!

**Pull request merged**
