### PR TITLE
Bugfix/default active note

### LINKED ISSUE #367: [Bug] Default active note in each folder should be the top note
**To Reproduce**
Create some notes, change the sorting behavior, and move between the folders

**Expected behavior**
In each category or folder, the first note selected should be the note at the top

**Actual behavior**
It varies by sorting behavior

### PR DESCRIPTION
**Pull request by machadolucasvp**
## Description

Closes #367 

1. Active/selected note will automatically be updated when sort behaviour is changed in settings
2. Active/selected note will automatically be updated according to sort order when the notes are loaded for the first time 
3. Swap folders now update active/selected note according to sort order
4. Swap category now update active/selected note according to sort order

Overall:
- Default active/selected note will be always the top one

### Browser checklist

This PR has been tested in the following browsers:

- [x] Chrome
- [x] Firefox
- [ ] Safari

### Testing checklist

- [ ] End-to-end tests have been created if necessary

### CODE REVIEW

**Comment by taniarascia** [comment]
@machadolucasvp Any progress on this?

**Comment by machadolucasvp** [comment]
I had already finished the work, it was an unusual week and ended up forgetting to mark as ready for review, sorry @taniarascia

**Comment by taniarascia** [comment]
I tested it out, but it seems a bit buggy and doesn't always work. :-/ For example, with lastUpdated, the welcome note would always be selected.

**Comment by taniarascia** [comment]
Remove line 450 of note.test.ts:

```
holdKeyAndClickNoteAtIndex(0, 'meta')
```

And the test will pass.

**Comment by taniarascia** [comment]
Thank you for tackling this bug!

**Comment by machadolucasvp** [comment]
Thanks for the tip @taniarascia. Sometimes in my local, when creating new note in `cypress` notes test, the 2nd note created is not beign the top one (default `Last Updated` sort option is selected), breaking severals tests that use `multiselect` feature. I couldn't reproduce this behaviour manually.

**Comment by machadolucasvp** [comment]
I updated the description of the PR, adding what it does.

For solve (2) and (3) was needed to access `settings` reducer data in `notes` reducer. I decided to pass down this information in the actions that need it because there were few. Since this is centralized in `getFirstNoteId` maybe configure and use `getState()` from `redux-thunk`  would be a better solution for the future, what you think about it ?

**Comment by taniarascia** [comment]
@machadolucasvp I think you're right. That would be a good refactor. It would be nice if it was easier to access state between slices. We'll watch out for any of those issues you mentioned in the meantime. Thanks again for your work on this!

**Review by taniarascia — APPROVED** [review]

**Comment by machadolucasvp** [comment]
Hey @taniarascia, i realized that there is a session for all contributors, sorry, but did you end up forgetting?

**Comment by taniarascia** [comment]
My bad, I wish it would happen automatically.

**Comment by taniarascia** [comment]
@all-contributors add @machadolucasvp for code, bug, test

**Comment by machadolucasvp** [comment]
Thanks o/

**Pull request merged**
