### PR TITLE
Refactor fix for issue  #226 Move String Literals

### PR DESCRIPTION
**Pull request by code128**
Hello,  

I have a PR here that moves the string literals out into their own resourceStrings.ts file. 

It doesn't seem to be passing the existing tests, but I'm not really sure where to look or how to fix that. 

Thanks!
Josh

#226

### CODE REVIEW

**Comment by taniarascia** [comment]
In `jest.config.js`, there is another alias module mapper.

```js
 moduleNameMapper: {
    // Allow `@/` to map to `src/client/` in Jest tests
    '@/(.*)$': '<rootDir>/src/client/$1',
    '@resources(.*)$': '<rootDir>/src/resources/$1', // <-- Add this line
  },
```

Add that line and the test will pass.

**Comment by taniarascia** [comment]
It seems the e2e tests need to be updated to pull from the shared resources.

**Comment by code128** [comment]
Yay, It's now passing! 

As a note I'm unable to run the Cypress tests locally for some reason. If I follow the README and try to run 
`npm run e2e:open` It opens a  Cypress window on my mac (v3.8.2) but doesnt seem to start up an instance of Takenote or whatever else might be needed.

**Comment by taniarascia** [comment]
@code128 Hi! In order to run the e2e tests, you have to have TakeNote running in one terminal window, and run the e2e command in another. I should make that more clear in the README. When I’m back at a computer, I’ll double check that it works then merge this in. Thanks!

**Comment by taniarascia** [comment]
@all-contributors please add @code128 for code

**Pull request merged**
