### PR TITLE
Add title attributes to NoteMenuBar buttons

### LINKED ISSUE #456: [Feature]
**Problem**
Upon first use, it can be tricky to understand what the buttons in the Note Menu Bar do.

**Solution**
By adding a title attribute to the button with a name for the button, users could hover over the button and see what the intent of the button is, whether its for Markdown Preview, Download, etc.

### PR DESCRIPTION
**Pull request by bjankord**
## Description

Closes #456 

### Browser checklist

This PR has been tested in the following browsers:

- [x] Chrome
- [x] Firefox
- [x] Safari

### Testing checklist

- [ ] End-to-end tests have been created if necessary

I have not added tests for this feature but I can if needed.

### CODE REVIEW

**Review by prashantswami — APPROVED** [review]
Looks good

**Comment by prashantswami** [comment]
I was wondering. If this adds actual tooltip. But title attribute is just fine.

**Comment by bjankord** [comment]
cc/ @taniarascia

**Comment by taniarascia** [comment]
I would prefer an actual tooltip be created rather than the `title` attribute.

**Comment by bjankord** [comment]
@taniarascia Do you want me to pull in a react tooltip package? Or should I make it a CSS only tooltip? Any design direction on how to tooltip works, I'm guessing have it work similar to how the title attribute tooltip works?

**Comment by taniarascia** [comment]
Sorry for the delay with this. If you want to just bring it up to date with master and keep the `title` attributes for now, it should be good to go. We can make more front end friendly tooltips in an additional PR.

**Comment by taniarascia** [comment]
Closing due to inactivity.

**Pull request closed without merging**
