### PR TITLE
Sidebar accessibility

### LINKED ISSUE #503: [Bug] Accessibility - Keyboard Navigation
https://takenote.dev/app

**To Reproduce**
Attempt to navigate the app without a mouse.

**Expected behavior**
Should be able to access all features sans mouse.

**Actual behavior**
There are several instances where using the `tab` key results in the focus of an item without highlighting it. This hinders users further who can only access the app using a keyboard. You are also essentially trapped in the editor if you are using it with only a keyboard. There is an exception, however, where you can use certain keyboard shortcuts (such as `Ctrl + Atl + F`) as an escape.

**Notes**

More reading in issue #495. You also lose the ability to use the `tab` key for navigation when editing a note. Take the Github editor as an example, where using the `tab` key escapes you from the editor, instead of writing out a tab. Adding tabs is a pain in these types of text editors, where adding 4 spaces is used as a replacement when writing inline code, etc.

There appear to be many opportunities to improve this throughout, such as allowing a user to navigate available notes using arrow keys.

### PR DESCRIPTION
**Pull request by Bartek532**
## Description

This PR provide support for keyboard users to move around sidebar links, I catch some more places when keyboard is not enough to use app and I will take care of it if this PR is approved 😁

Partly Closes #503 

### Browser checklist

This PR has been tested in the following browsers:

- [x] Chrome
- [x] Firefox
- [ ] Safari

### CODE REVIEW

**Comment by taniarascia** [comment]
Sorry for the delay on reviewing this. Thanks for this! Looks great. The only major thing I notice is that the "Create Category" button doesn't have a focus state so it's not clear that's selected (my bad. This is a big improvement.

**Comment by taniarascia** [comment]
@all-contributors add @Bartek532 for code

**Comment by Bartek532** [comment]
Thanks for the approve! I mentioned before that there are a few more places where the keyboard support is not sufficient, can I take care of this? 😁

**Comment by Bartek532** [comment]
@taniarascia

**Pull request merged**
