### PR TITLE
sort categories by name in select

### PR DESCRIPTION
**Pull request by Mudassar045**
It will make easy to select the desired category

### CODE REVIEW

**Comment by Mudassar045** [comment]
Adding sort functionality to categories name, causing this error on clicking categories names, notes etc on creating a new category.

```
A state mutation was detected between dispatches, in the path `categoryState.categories.2`. This may cause incorrect behavior. (http://redux.js.org/docs/Troubleshooting.html#never-mutate-reducer-arguments)
```
This is happening due to `Mutating Categories State` while sorting category names in `sidebar`. I'm beginner to React, unable to know the exact cause of happening this.

**Comment by taniarascia** [comment]
The sort method causes a mutation.

**Comment by Mudassar045** [comment]
> The sort method causes a mutation.

Yes, you're right. `sort()` causes mutations.
Here are the ways, I found which can serve  the sorting purpose
 -  make a copy of original categories array
 - sort the categories before the state update method

**Comment by taniarascia** [comment]
Categories can be in the same order everywhere. Perhaps later I'll introduce the ability to drag and drop sort the categories.

**Pull request closed without merging**
