### PR TITLE
Multi select

### LINKED ISSUE #231: [Feature] Bulk actions on notes
**Problem**
Organizing a lot of notes is hard when handling one by one.

**Solution**
First:
- [ ] Add ability to multi-select notes and drag them into a category (or All Notes, Favorites, Trash)

Stretch
- [ ] New UI element with menu to do a bulk action on these notes (Move to Trash, Favorite, etc)
- [ ] Multi select categories and delete (with new UI element)
- [ ] Multi select categories and drag to trash

**Note**
Accompany added functionality with tests, and prefer comments for any complex logic

### PR DESCRIPTION
**Pull request by Mxchaeltrxn**
## Description

It is not yet finished but I have made some changes to existing code and would like some feedback on whether or not I am heading in the right direction.

Fixes #231
Features implemented so far are notes multiselection, batch deletion and batch favouriting via the right click UI option.
I still need to implement batch download and batch 'moveToCategory', batch dnd and tests.

## Browser Checklist

This PR has been tested in the following browsers:

- [ ] Chrome
- [x] Firefox
- [ ] Safari

I will do the rest when I finish this pr.

## Other
- I'm not quite sure why the category test is failing. What I find strange is that the integration tests don't always return the same thing when I run it and it's failing on my master branch as well. I have not used Cypress before. Do you know why this is happening? If not, I can look into this when I start testing 
- Should 'swapNote' in notes slices (line 119 in /src/client/slices/notes.ts in this branch) be renamed 'updateActiveNote'? This feels more accurate to me
- Note: I implemented the UI feature before the drag and drop because it was easier to do and I plan on doing both anyway

### CODE REVIEW

**Comment by taniarascia** [comment]
Hi! This is looking great. It took me a while to figure out what I was supposed to do to multi-select, because I kept trying to shift and click to get a group instead of command and click to individually select, but it makes total sense. 

Changing `swapNote` to `updateActiveNote` makes sense to me, as long as `swapCategory` is also updated to `updateActiveCategoryId` to match. 

The test is failing because the actual action is failing - if you create a category, create a note, and click "Move to category", select the category that you've just created, and go to the category, nothing is there. The note has a category uuid associated with it but is not appearing in the UI. The issue exists on line 73-74 of NoteList:

```js
const filteredNotes: NoteItem[] = notes
    .filter(filter[activeFolder])
```

This is attempting to filter out all notes that don't exist in the current folder.

If the folder is `CATEGORY`, it filters thus: 

```js
[Folder.CATEGORY]: note => !note.trash && note.category === activeCategoryId,
```

However, this added `categoryId` instead of `category` to the note properties.

**Comment by Mxchaeltrxn** [comment]
Hey! Thanks for the detailed reply and checking for me. I should have mentioned I designed it to use command only. It seems like adding the shift functionality will be kind of interesting/difficult (I'm modelling most of what I do off of apple notes).

Also is there a reason why we use type `Record` instead of something like {[key]: any}?

Wow I think I fixed that bug. It was such a nightmare to fix that typo. I must have thought the field was categoryId and not category. I might go ahead and change category to categoryId.

**Comment by Mxchaeltrxn** [comment]
Batch drag and drop into trash and favourites and renaming swapActiveNoteId and swapFolder need to be done. Oh I haven't tested it in safari either.

I am thinking of doing this https://stackoverflow.com/questions/10527983/best-way-to-detect-mac-os-x-or-windows-computers-with-javascript-or-jquery to detect whether to use metaKey or control (for selecting multiple elements). Alternatively, I could just use control because the keyboard shortcuts don't seem to cater to mac users right now anyway. If we did go down the metaKey route, I'm not quite sure how to test both metaKey and ctrl in the tests.

So I was thinking of implementing the shift select but the way I'm thinking of implementing it seems to add a lot of code. What do you think of the way that shift click is implemented in apple Notes or Finder (I think they're both implemented the same way)?

**Comment by taniarascia** [comment]
I would rather cater the keys to Mac users, as a Mac user. 😄 I think the way you have it already is nice.  Making the shift and command behavior similar to Notes/Finder would be nice, but if it's too much to add to start, it could always be something we add on after getting the initial PR in.

**Comment by taniarascia** [comment]
Hiya, wondering if there are any status updates on this? Haven't wanted to make any big changes in case it conflicts with what you're doing here.

**Comment by Mxchaeltrxn** [comment]
Hey sorry about that. I'll push the changes up in a moment

**Comment by Mxchaeltrxn** [comment]
Hey Tania! Sorry about that. I'm going to be a lot busier now but I'll see what I can do from now on. I've just made a few changes to the branch.

This branch does not seem to work on Chrome and Safari and it's unclear to me why. In the onClick attribute on line 213 of containers/NoteList.ts, when I add a console.log to that function, it doesn't show up when I click on a note in Chrome and Safari. Despite this, it still seems to update the active note (line 217?).

That being said I can have a look later and it works on Firefox so I think it can be merged for now so it doesn't block development. 

What still needs to be done is the drag and drop, shift click functionality and fixing the behaviour in Chrome and Safari.

**Comment by taniarascia** [comment]
Hi @Mxchaeltrxn! Totally understand that you're busy. Just wanted to make sure that your work got merged in.

I tested the following on Chrome, Safari, and Firefox without an issue: (dropdown only)

- Toggling favorite (the behavior is a bit confusing because it toggles, but you can only see add or remove, so if the text is changed to say toggle instead, it'll be perfect).
- Adding to trash/removing from trash
- Moving to category/removing from category

What did you find that wasn't working for Chrome/Safari, so I can help debug? 

I was also able to drag and drop multiple notes into a category, but not able to drag and drop multiple notes into trash or favorite, so I can take a look at that...

**Comment by taniarascia** [comment]
I made a new branch so I can make updates, so I'm closing this one.

**Comment by Mxchaeltrxn** [comment]
@taniarascia command + click wasn't working on chrome and safari for me. If it works for you, it might be related to some browser settings of mine?

So I actually didn't write the functionality to allow it to drag multiple notes into a category—it already worked after I implemented the multi select, which was nice but I haven't actually looked at the code to make sure nothing unintended is happening.

**Comment by taniarascia** [comment]
I tested the live site on Safari and Chrome on a new computer with default settings, and it’s working for me. Is the live site not working for you on any browser now? I’ve been testing all the drag and drop and everything seems to be good! The only thing that isn’t inplemented is shift click, which I think is fine.

**Comment by Mxchaeltrxn** [comment]
It works. I meant that it didn't work when I tested it locally ... That's strange. I'll see how things go when I pull the latest master 😀

**Pull request closed without merging**
