### PR TITLE
Sync test welcome note test

### PR DESCRIPTION
**Pull request by codytowstik**
This should go in after the previous PR

### CODE REVIEW

**Comment by taniarascia** [comment]
Just a heads up, I got the CI/CD pipeline set up for the server based version, so will be merging that in shortly, before these other PRs (trying to avoid fixing all the merge conflicts again and putting it off longer).

**Comment by codytowstik** [comment]
I don't mind waiting for the big PR to go through that you are making, these mods are more straightforward and should be easy to reconcile.

**Comment by taniarascia** [comment]
It’s all finished at the moment. The actual auth aspect isn’t implemented, but the structural changes are. I don’t think it should be too difficult to bypass auth once that’s done, either.

**Comment by codytowstik** [comment]
All set for review.

When this goes in I can finish up the last two tests for this issue:
https://github.com/taniarascia/takenote/issues/73

**Pull request merged**
