### PR TITLE
Confirm exit

### LINKED ISSUE #78: [Feature] Pop up to confirm exit ?

### PR DESCRIPTION
**Pull request by BastianKubaile**
Fixes #78 by using  [react-beforeunload ](https://github.com/jacobbuck/react-beforeunload).

### CODE REVIEW

**Comment by Jfelix61** [comment]
Thanks for the contribution! I think adding the unload on app will just make the user annoyed since it will popup every single time. I believe it should be done in the period when the notes are not synced with the local storage.

**Comment by BastianKubaile** [comment]
Ok, I will look into this. As I am currently new to React/ Redux it might take a will for me to figure it out though ;)

**Comment by Jfelix61** [comment]
> Ok, I will look into this. As I am currently new to React/ Redux it might take a will for me to figure it out though ;)

Thanks, we sync on [KeyboardShortcuts.ts](https://github.com/taniarascia/takenote/blob/99c2cd053b/src/containers/KeyboardShortcuts.tsx) inside the useInterval function; maybe you could check if there are pending changes by using a boolean on the redux store, and, if true, then it displays the alert.

**Comment by BastianKubaile** [comment]
Thanks for the hint

**Comment by taniarascia** [comment]
There's also a "syncing" state. Sync happens every 20 seconds, so a combination of checking if the last update happened within 20 seconds and data is syncing would be a good idea.

**Comment by taniarascia** [comment]
Closing stale issue.

**Pull request closed without merging**
